  version: '3'
  services:
    
    laravel:
      image: felipeesc91/laravel
      container_name: laravel
      networks:
        - laranet
    
    nginx:
      image: felipeesc91/nginx:prod
      container_name: nginx
      networks:
        - laranet
      ports:
        - "8080:80"
    
    networks:
      laranet:
        driver: bridge